{{- if .Values.frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:      
        {{- toYaml . | nindent 8 }}
      {{- end }}    
      containers:
      - name: {{ .Values.frontend.name }}
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        volumeMounts:
        - name: storage
          mountPath: "/app/frontend/static/reports"
          readOnly: true
        ports:
        - containerPort: 5002
        env:
        - name: FRONTEND_PREFIX
          value: {{ .Values.frontend.applicationPrefix }}
        - name: FRONTEND_NAME
          value: {{ .Values.frontend.applicationName }}
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaim.name }}
{{- end -}}